<?php

namespace GrillBundle\Repository;

/**
 * GrillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrillRepository extends \Doctrine\ORM\EntityRepository
{
}
