grill:
    resource: "@GrillBundle/Resources/config/routing.yml"
    prefix:   /

homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

race:
    resource: "@RaceBundle/Resources/config/routing.yml"
    prefix:   /


