ry_g_place:
    resource: "@RyGBundle/Controller/PlaceController.php"
    type:     annotation

gallery_image:
    resource: "@GalleryBundle/Controller/ImageController.php"
    type:     annotation

ry_g_griller:
    resource: "@RyGBundle/Controller/GrillerController.php"
    type:     annotation

ry_g_runner:
    resource: "@RyGBundle/Controller/RunnerController.php"
    type:     annotation

ry_g_edition:
    resource: "@RyGBundle/Controller/EditionController.php"
    type:     annotation

ry_g:
    resource: "@RyGBundle/Resources/config/routing.yml"
    prefix:   /

main:
    resource: "@RyGBundle/Controller/MainController.php"
    type:     annotation
