<?php

namespace RyGBundle\Repository;

/**
 * GrillerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrillerRepository extends \Doctrine\ORM\EntityRepository
{
}
