race_homepage:
    path:     /race
    defaults: { _controller: RaceBundle:Race:index }

    
race_index:
    path: /race/index
    defaults: { _controller: RaceBundle:Race:index }
    
race_add:
    path: /race/add
    defaults: { _controller: RaceBundle:Race:add }

race_create:
    path: /race/create
    defaults: { _controller: RaceBundle:Race:create }
    methods: [POST]
    
race_edit:
    path: /race/edit/{id}
    defaults: { _controller: RaceBundle:Race:edit }
    
race_update:
    path: /race/update/{id}
    defaults: { _controller: RaceBundle:Race:update }
    methods:  [POST, PUT]
    
race_activate:
    path: /race/activate/{id}
    defaults: { _controller: RaceBundle:Race:activate }
    
race_start:
    path: /race/start/{id}
    defaults: { _controller: RaceBundle:Race:start }
    
runner_index:
    path: /runner/index
    defaults: { _controller: RaceBundle:Runner:index }
    
runner_edit:
    path: /runner/edit
    defaults: { _controller: RaceBundle:Runner:edit }
    
runner_update:
    path: /runner/update
    defaults: { _controller: RaceBundle:Runner:update }
    methods:  [POST, PUT]
    
race_activate:
    path: /race/activate/{id}
    defaults: { _controller: RaceBundle:Race:activate }

runner_chrono:
    path: /runner/chrono/{code}
    defaults: { _controller: RaceBundle:Runner:chrono }