race_homepage:
    path:     /race
    defaults: { _controller: RaceBundle:Race:index }

    
race_index:
    path: /race/index
    defaults: { _controller: RaceBundle:Race:index }

race_activate:
    path: /race/activate/{id}
    defaults: { _controller: RaceBundle:Race:activate }
    
race_start:
    path: /race/start/{id}
    defaults: { _controller: RaceBundle:Race:start }
    
runner_index:
    path: /runner/index
    defaults: { _controller: RaceBundle:Runner:index }

runner_chrono:
    path: /runner/chrono/{code}
    defaults: { _controller: RaceBundle:Runner:chrono }