race_homepage:
    path:     /
    defaults: { _controller: RaceBundle:Default:index }

    
race_index:
    path: /race/index
    defaults: { _controller: RaceBundle:Race:index }

race_activate:
    path: /race/activate/{id}
    defaults: { _controller: RaceBundle:Race:activate }    